### ISSUE TITLE
HM-ES-TX-WM

### ISSUE THREAD

**Issue by twendt** [twendt/homey-matic#27]

**Comment by twendt** [comment]
@sebi28 I added the device to branch 0.16.0. Would you be able to test it by manualy installing the app from the branch? I am not sure what the IEC_ENERGY_COUNTER and IEC_POWER are used for and why there are 2 channels with these datapoints. I did not implement them.

**Comment by sebi28** [comment]
@twendt Thanks for adding this device! I might explain a bit about the HM-ES-TX-WM.
The device can be connected to four different sensors. These sensors can be used to receive optical information of a power or gas meter / counter. One of these sensors can be attachted to a smart meter which might send a few different values. The protocol is named IEC 62056-21. So, it would make sense to include at least four IEC values, if possible:
Energy received from the energy provider:
- Actual power in Watt
- Counted power in kWh
Energy "sold" to the energy provider (via e.g. solar energy / photovoltaics)
- Actual power in Watt
- Counted power in kWh

Right now, I can only test the IEC sensor.

Again, thanks for your support!

**Comment by twendt** [comment]
0.16.0 includes the "broken" implementation. With 0.17.0 I will somehow include the IEC sensors.

**Comment by twendt** [comment]
Please give it a try again. I implemented it as 2 devices now. You have to rejoin the device to get the new features. Hopefully that work.

**Comment by sebi28** [comment]
I've just tested the new version but it does not show up any values inside the homey app. Just a second thing to metion: As far as I know, the IEC sensor will not work as a gas counter. So, these values can be removed.

**Comment by twendt** [comment]
Did you delete the device and paired again?

**Comment by sebi28** [comment]
Sorry for the delay!
Yes, I've deleted and reconnected the device, but it's still not showing any values.
